### ISSUE TITLE
Program compile error on uncommenting DEBUG_PRINT

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cniweb/gsm-playground#1]
```
Hi

Have an issue when runnning the new GPRS code with debug
1. Import libraries from r7 and AT.cpp from r4
2. Uncomment //#define DEBUG_PRINT in GSM.h 
3. Open GPRS_basic.pde
4. Compile Program 
5. Compile error complaining about an undefined reference to AT :: debugprint

Using Artuino 021 software

Thanks

Colin


```

Original issue reported on code.google.com by `ctcray...@yahoo.co.uk` on 14 Jan 2011 at 10:01

Attachments:
* [screenshot.JPG](https://storage.googleapis.com/google-code-attachments/gsm-playground/issue-1/comment-0/screenshot.JPG)

**Comment by cniweb** [comment]
Fixed with commit d0561392fa02f5364376512e849c200fd9f0216c
